require('./plant');
require('./plantType');
require('./sunlight');
require('./exposure');
require('./aspect');
require('./foliage');
require('./habit');
require('./moisture');
require('./ph');